marttiphpbb_topicsuffixtags_defaultview_controller:
    pattern: /topicsuffixtags
    defaults: { _controller: marttiphpbb.topicsuffixtags.controller:defaultview }
    requirements:
        _method: GET

marttiphpbb_topicsuffixtags_yearview_controller:
    pattern: /topicsuffixtags/{year}
    defaults: { _controller: marttiphpbb.topicsuffixtags.controller:yearview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$

marttiphpbb_topicsuffixtags_monthview_controller:
    pattern: /topicsuffixtags/{year}/{month}
    defaults: { _controller: marttiphpbb.topicsuffixtags.controller:monthview }
    requirements:
        _method: GET
        year: ^(19|20)[0-9]{2}$
        month: ^[1-9]|1[012]$

