services:
    marttiphpbb.topicprefixtags.listener:
        class: marttiphpbb\topicprefixtags\event\listener
        arguments:
            - '@template'
            - '@marttiphpbb.topicprefixtags.service.tags'
        tags:
            - { name: event.listener }

    marttiphpbb.topicprefixtags.service.tags:
        class: marttiphpbb\topicprefixtags\service\tags
        arguments:
            - '@dispatcher'
