services:
    marttiphpbb.topicsuffixtags.main_listener:
        class: marttiphpbb\topicsuffixtags\event\main_listener
        arguments:
            - '@controller.helper'
            - '%core.php_ext%'
            - '@template'
            - '@language'
            - '@marttiphpbb.topicsuffixtags.render.links'
        tags:
            - { name: event.listener }

    marttiphpbb.topicsuffixtags.tag_listener:
        class: marttiphpbb\topicsuffixtags\event\tag_listener
        arguments:
            - '@template'
            - '@marttiphpbb.topicsuffixtags.render.tag'
        tags:
            - { name: event.listener }

    marttiphpbb.topicsuffixtags.posting_listener:
        class: marttiphpbb\topicsuffixtags\event\posting_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@marttiphpbb.topicsuffixtags.render.include_assets'
            - '@marttiphpbb.topicsuffixtags.render.input_settings'
            - '@marttiphpbb.topicsuffixtags.render.posting'
        tags:
            - { name: event.listener }

    marttiphpbb.topicsuffixtags.controller:
        class: marttiphpbb\topicsuffixtags\controller\main
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '%core.php_ext%'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '%core.root_path%'
            - '@marttiphpbb.topicsuffixtags.core.event_container'
            - '@marttiphpbb.topicsuffixtags.moonphase_calculator'
            - '@marttiphpbb.topicsuffixtags.timeformat'
            - '@marttiphpbb.topicsuffixtags.render.render_settings'
            - '@marttiphpbb.topicsuffixtags.render.pagination'

    marttiphpbb.topicsuffixtags.core.event_container:
        class: marttiphpbb\topicsuffixtags\core\event_container
        arguments:
            - '@auth'
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '%tables.topics%'

    marttiphpbb.topicsuffixtags.moonphase_calculator:
        class: marttiphpbb\topicsuffixtags\util\moonphase_calculator

    marttiphpbb.topicsuffixtags.timeformat:
        class: marttiphpbb\topicsuffixtags\util\timeformat
        arguments:
            - '@user'

    marttiphpbb.topicsuffixtags.render.links:
        class: marttiphpbb\topicsuffixtags\render\links
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.topicsuffixtags.render.include_assets:
        class: marttiphpbb\topicsuffixtags\render\include_assets
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '%core.root_path%'

    marttiphpbb.topicsuffixtags.render.render_settings:
        class: marttiphpbb\topicsuffixtags\render\render_settings
        arguments:
            - '@config'
            - '@template'
            - '@language'

    marttiphpbb.topicsuffixtags.render.pagination:
        class: marttiphpbb\topicsuffixtags\render\pagination
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@language'

    marttiphpbb.topicsuffixtags.render.input_settings:
        class: marttiphpbb\topicsuffixtags\render\input_settings
        arguments:
            - '@config'
            - '@config_text'
            - '@template'
            - '@language'

    marttiphpbb.topicsuffixtags.render.input_settings:
        class: marttiphpbb\topicsuffixtags\render\input_settings
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.topicsuffixtags.render.input_settings'
            - '@marttiphpbb.topicsuffixtags.render.include_assets'

    marttiphpbb.topicsuffixtags.render.tag:
        class: marttiphpbb\topicsuffixtags\render\tag
        arguments:
            - '@controller.helper'
            - '@marttiphpbb.topicsuffixtags.dateformat'

    marttiphpbb.topicsuffixtags.render.posting:
        class: marttiphpbb\topicsuffixtags\render\posting
        arguments:
            - '@config'
            - '@template'
            - '@language'
            - '@marttiphpbb.topicsuffixtags.render.input_settings'
            - '@marttiphpbb.topicsuffixtags.render.include_assets'

    marttiphpbb.topicsuffixtags.dateformat:
        class: marttiphpbb\topicsuffixtags\util\dateformat
        arguments:
            - '@user'
            - '@language'
