services:
    marttiphpbb.topicsuffixtags.listener:
        class: marttiphpbb\topicsuffixtags\event\listener
        arguments:
            - '@template'
            - '@marttiphpbb.topicsuffixtags.service.tags'
        tags:
            - { name: event.listener }

    marttiphpbb.topicsuffixtags.service.tags:
        class: marttiphpbb\topicsuffixtags\service\tags
        arguments:
            - '@dispatcher'
